version: 0.2
# //teste
phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm ci
      # - npm install
  pre_build:
    commands:
    #  export CYPRESS_VERIFY_TIMEOUT=60000 
    #   - npm run cy:verify
    #   - npm run cy:info
  build:
    commands:
      # - npm run start:ci &
      # - npx cypress run --record
      - npm run open